# @Author: Michael Harrison, guiguan, koustubhg
# @Date:   2019-04-10T23:00:00+10:00
# @Last modified by:   guiguan
# @Last modified time: 2019-04-12T23:25:50+10:00

# update pipeline:
# fly -t dev sp -c pipeline-deploy.yml -p provendocs-deploy
---
resource_types:
  - name: gcs-resource
    type: docker-image
    source:
      repository: frodenas/gcs-resource
  - name: slack-alert
    type: docker-image
    source:
      repository: southbanksoftware/concourse-slack-alert-resource
  - name: github-status
    type: docker-image
    source:
      repository: dpb587/github-status-resource
      tag: master

resources:
  - name: slack
    type: slack-alert
    source:
      url: ((common.slack-webook-url))
  - name: github-status
    type: github-status
    source:
      repository: SouthbankSoftware/provendocs
      access_token: ((common.git-access-token))
      branch: develop
      context: deploy
  - name: provendocs
    type: git
    check_every: 5m
    webhook_token: ((common.webhook-token))
    source:
      uri: https://github.com/SouthbankSoftware/provendocs.git
      branch: develop
      username: ((common.git-username))
      password: ((common.git-password))
      disable_ci_skip: false
  - name: version
    type: semver
    source:
      driver: gcs
      bucket: provendb-ci
      json_key: ((common.service-account))
      key: provendocs/version/version.txt
      initial_version: 0.0.0
  - name: docker-registry
    type: docker-image
    source:
      repository: asia.gcr.io/provendb/provendocs
      username: _json_key
      password: ((common.service-account))

jobs:
  - name: build-and-deploy
    serial: true
    plan:
      - get: provendocs
        trigger: true
      - put: github-status
        params:
          commit: provendocs
          state: pending
      - get: version
        params: { bump: patch }
      - put: docker-registry
        params:
          additional_tags: provendocs/.git/short_ref
          build: provendocs
          tag_as_latest: true
          tag_file: version/number
        get_params: { skip_download: true }
      - put: version
        params: { file: version/number }
    on_failure:
      do:
        - put: slack
          params:
            alert_type: failed
            text: ((slack.mike)), ((slack.wahaj))
        - put: github-status
          params:
            commit: provendocs
            state: failure
    on_abort:
      do:
        - put: slack
          params:
            alert_type: failed
            text: Aborted. ((slack.mike)), ((slack.wahaj))
        - put: github-status
          params:
            commit: provendocs
            state: failure
    on_success:
      do:
        - put: slack
          params:
            alert_type: success
        - put: github-status
          params:
            commit: provendocs
            state: success
