# provendocs
# Copyright (C) 2019  Southbank Software Ltd.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#
# @Author: koustubhg, guiguan
# @Date:   2019-04-11T14:59:30+10:00
# @Last modified by:   guiguan
# @Last modified time: 2019-04-11T14:59:39+10:00

# update pipeline:
# fly -t dev sp -c pipeline-test.yml -p provendocs-test
---
resource_types:
  - name: gcs-resource
    type: docker-image
    source:
      repository: frodenas/gcs-resource
  - name: slack-alert
    type: docker-image
    source:
      repository: southbanksoftware/concourse-slack-alert-resource
  - name: cron-resource
    type: docker-image
    source:
      repository: cftoolsmiths/cron-resource

resources:
  - name: provendocs-tests
    type: git
    source:
      uri: https://github.com/SouthbankSoftware/provenDocs-tests.git
      branch: master
      username: ((common.git-username))
      password: ((common.git-password))
  - name: node
    type: docker-image
    source:
      repository: node
  - name: seleniumhub
    type: docker-image
    source:
      repository: selenium/hub
      tag: "latest"
  - name: chromenode
    type: docker-image
    source:
      repository: selenium/node-chrome
      tag: "latest"
  - name: provendocs-test-reports
    type: gcs-resource
    source:
      bucket: provendocs-tests
      json_key: ((common.service-account))
      versioned_file: result.tar.gz
      file: result.tar.gz
  - name: nightly-build
    type: cron-resource
    source:
      expression: "30 4 * * *"
      location: "Australia/Melbourne"
      fire_immediately: true
  - name: slack
    type: slack-alert
    source:
      url: ((common.slack-webook-url))

jobs:
  - name: test-nightly
    plan:
      - get: nightly-build
        trigger: true
      # aggregate 3 resources at a time (bounded parallelism)
      - aggregate:
          - get: provendocs-tests
          - get: seleniumhub
            params: { save: true }
      - aggregate:
          - get: chromenode
            params: { save: true }
          - get: node
            params: { save: true }
      - task: runSelenium-tests
        privileged: true
        file: provendocs-tests/ci/tasks/runSelenium-tests.yml
      - put: provendocs-test-reports
        params:
          file: output/result.tar.gz
          content_type: application/octet-stream
          outputs:
            - results
        on_success:
          put: slack
          params:
            alert_type: success
            text: Download result.tar.gz from here https://console.cloud.google.com/storage/browser/provendocs-tests?project=provendb
      - task: update-build-status #Need this step to update build status
        config:
          inputs:
            - name: results
            - name: provendocs-tests
          platform: linux
          image_resource:
            type: docker-image
            source: { repository: alpine, tag: 3.9 }
          run:
            path: sh
            args:
              - -exc
              - |
                chmod a+x provendocs-tests/ci/decideBuildStatus.sh 
                chmod a+r results/junit.xml
                sh provendocs-tests/ci/decideBuildStatus.sh results/junit.xml
    on_failure:
      put: slack
      params:
        alert_type: failed
        text: ((slack.virender))
    on_abort:
      put: slack
      params:
        alert_type: failed
        text: Aborted. ((slack.virender))
    on_success:
      put: slack
      params:
        alert_type: success
